---
title: Vercel Configuration
description: Complete Vercel setup and configuration guide for IdeaI monorepo, including dashboard settings, project setup, and deployment processes.
---

# Vercel Configuration

Complete guide for configuring and deploying IdeaI monorepo apps to Vercel.

## Project Information

- **Organization**: `idea-i`
- **Organization ID**: `team_vhjzlMi6CfNow0IfBXnv2Yn2`
- **Main Project**: `web` (deploys `apps/web`)
- **Production URL**: https://www.myui.space

## Required Dashboard Settings

**⚠️ CRITICAL**: These settings must be configured correctly for each app or deployment will fail.

### General Settings

1. **Root Directory**: `apps/{app-name}`
   - Example: `apps/web`, `apps/docs`
   - ⚠️ **Must be relative to repo root** (not absolute path)
   - ⚠️ **NOT**: `apps/web/apps/web` (would duplicate path)

2. **Framework Preset**: Next.js (auto-detected)

3. **Build Command**: Auto-detected from `package.json`
   - Should be: `pnpm build` or `next build`

4. **Install Command**: Auto-detected
   - Should be: `pnpm install`

5. **Output Directory**: `.next` (Next.js default)

### Advanced Settings

1. **Include files outside the root directory in the Build Step**: ✅ **Enable**
   - **Required for monorepo setup**
   - Allows access to `packages/` and other shared code
   - Without this, Vercel can't access workspace dependencies

2. **Environment Variables**: Set as needed
   - `NEXT_PUBLIC_VERCEL_PROJECT_NAME` - Project name (shown in header)
   - `NEXT_PUBLIC_VERCEL_ORG_ID` - Organization ID (default: `idea-i`)

## Project-Specific Configuration

### Web App (Main Site)

**Project**: `web`  
**Root Directory**: `apps/web`  
**Production URL**: `myui.space`

**Required Settings**:
- ✅ Root Directory: `apps/web`
- ✅ Include files outside root: Enabled
- ✅ Install Command: `pnpm install`
- ✅ Build Command: `pnpm build`

### Docs App

**Project**: `docs`  
**Root Directory**: `apps/docs`  
**Production URL**: `docs-*.vercel.app`

**Required Settings**:
- ✅ Root Directory: `apps/docs`
- ✅ Include files outside root: Enabled
- ✅ Install Command: `pnpm install`
- ✅ Build Command: `pnpm build`

### Other Apps

All other apps (`all`, `nocss`, `mvp`, `tailwind`, `allcss`, `unocss`, `shadcn`) follow the same pattern:
- Root Directory: `apps/{app-name}`
- Include files outside root: Enabled
- Install Command: `pnpm install`
- Build Command: `pnpm build`

## Vercel CLI

### Installation

```bash
npm install -g vercel
```

### Authentication

```bash
vercel login
```

### Linking Projects

Projects are linked via `.vercel/` directory:

```bash
# From repository root (Vercel uses Root Directory setting)
vercel link
```

This creates `.vercel/project.json` with project configuration.

**Note**: Vercel uses the Root Directory setting (`apps/web`) from the dashboard, so link from the repo root.

### Manual Deployment

```bash
# From repository root
# Preview deployment
vercel deploy

# Production deployment
vercel deploy --prod
```

**Note**: Deploy from repo root. Vercel automatically uses the Root Directory setting (`apps/web`) from the dashboard.

### Environment Variables

Pull environment variables locally:

```bash
# From repository root
vercel env pull .env.local
```

The `.env.local` file will be created in the current directory. Vercel uses the Root Directory setting to determine which app's environment variables to pull.

## Monorepo Configuration

### Standard Turborepo + Vercel Approach

This project uses the **standard Vercel boilerplate approach** for Turborepo monorepos:

1. **Root Directory** set in Vercel dashboard: `apps/{app-name}`
2. **Include files outside root** enabled (required for monorepos)
3. **Deploy from repo root** (no `working-directory` in workflows)
4. **Vercel auto-detects** Next.js and builds automatically

**How it works:**
- Vercel uses the Root Directory setting to find the app
- "Include files outside root" allows access to monorepo root files
- Vercel automatically detects Next.js from `package.json`
- Build commands run from the monorepo root context
- Shared packages in `packages/` are accessible during build

### Framework Detection

Vercel automatically detects Next.js when:
- Root Directory is set correctly (`apps/{app-name}`)
- `package.json` contains `next` dependency
- "Include files outside root directory" is enabled

## Deployment Process

### Automatic Deployment

1. Code pushed to GitHub
2. GitHub Actions workflow triggered
3. Build and test steps run
4. Vercel deployment initiated
5. Preview/production URL generated

### Deployment URLs

- **Preview**: `https://{app}-{hash}-idea-i.vercel.app`
- **Production**: Custom domain or `https://{app}-{hash}-idea-i.vercel.app`

### Deployment Status

Check deployment status:
- [Vercel Dashboard](https://vercel.com/idea-i)
- GitHub Actions workflow logs
- Vercel CLI: `vercel inspect`

## Configuration Files

### .vercel/project.json

Generated by `vercel link`:

```json
{
  "projectId": "prj_...",
  "orgId": "team_vhjzlMi6CfNow0IfBXnv2Yn2",
  "projectName": "web"
}
```

## Troubleshooting

### "Unexpected error" or Build Fails

**Symptoms**: Deployment queues but fails with "Unexpected error" or module resolution errors

**Solution**: This is almost always caused by missing monorepo configuration:
1. Set Root Directory to `apps/{app-name}` in [Project Settings](https://vercel.com/idea-i/{app}/settings/general)
2. **Enable** "Include files outside the root directory in the Build Step" checkbox
3. Save and redeploy

Without the "Include files outside the root directory" setting, Vercel can't access:
- Root `package.json` and workspace configuration
- Shared packages in `packages/`
- `turbo.json` for build orchestration

### "No Next.js version detected"

**Solution**: 
1. Set Root Directory to `apps/{app-name}` in Vercel project settings
2. Enable "Include files outside the root directory in the Build Step"

### Build Fails: "Cannot find module '@repo/ui'"

**Solution**: 
1. Ensure "Include files outside the root directory in the Build Step" is enabled
2. Verify Root Directory is set to `apps/{app-name}`
3. Check workspace dependencies are properly configured in `package.json`

### Error: "npm install" exited with 1

**Cause**: Vercel is using npm instead of pnpm

**Fix**: 
1. Set `installCommand` in `vercel.json`:
   ```json
   {
     "installCommand": "pnpm install"
   }
   ```
2. Or set in Vercel dashboard: Settings → General → Install Command

### Error: Path does not exist

**Cause**: Root Directory is set incorrectly in Vercel dashboard

**Fix**:
1. Go to Vercel dashboard → Project Settings → General
2. Set Root Directory to: `apps/{app-name}` (e.g., `apps/docs`)
3. ⚠️ Do NOT include the full path or absolute paths
4. Just the relative path from repo root: `apps/docs`

### Deployment Canceled: "Unverified commit"

**Solution**: This is Vercel's deployment protection. Options:
1. **Disable verification requirement** (for preview): Go to Project Settings → Deployment Protection → Disable "Require Verified Commits"
2. **Set up commit signing** (recommended): Configure GPG signing for commits (see [Commit Signing Setup](../setup/commit-signing.md))

## Best Practices

- ✅ Set Root Directory to `apps/{app-name}` in Vercel dashboard
- ✅ **Enable "Include files outside the root directory in the Build Step"** (required for monorepos)
- ✅ Deploy from repo root in GitHub Actions (no `working-directory` parameter)
- ✅ Let Vercel auto-detect Next.js framework (no `vercel.json` needed)
- ✅ Use environment variables for secrets
- ✅ Test deployments on preview before production
- ✅ Use standard Turborepo + Vercel boilerplate approach

## Quick Reference

| App | Root Directory | Project Name | Status |
|-----|---------------|--------------|--------|
| web | `apps/web` | `web` | ✅ Deployed |
| docs | `apps/docs` | `docs` | ✅ Deployed |
| all | `apps/all` | `all` | Ready |
| nocss | `apps/nocss` | `nocss` | Ready |
| mvp | `apps/mvp` | `mvp` | Ready |
| tailwind | `apps/tailwind` | `tailwind` | Ready |
| allcss | `apps/allcss` | `allcss` | Ready |
| unocss | `apps/unocss` | `unocss` | Ready |
| shadcn | `apps/shadcn` | `shadcn` | Ready |

## Related Documentation

- [Deployment Overview](./overview.md)
- [Unified Deployment Guide](./unified-deployment.md) - **Start here** for deployment
- [CI/CD Workflows](./ci-cd.md)
- [GitHub Secrets Setup](../setup/github-secrets.md)
- [Vercel Checklist](../setup/vercel-checklist.md)
