---
title: Vercel Configuration
description: Vercel deployment configuration for the IdeaI monorepo, including project setup, monorepo configuration, and deployment processes.
---
# Vercel Configuration

This document describes the Vercel deployment configuration for this monorepo.

## Project Information

- **Organization**: `idea-i`
- **Organization ID**: `team_vhjzlMi6CfNow0IfBXnv2Yn2`
- **Project Name**: `ideai-main` (deploys `apps/web`)
- **Project ID**: `prj_Se4sFOjdH4fRzSOsK8YDiNVFssHx`
- **Production URL**: https://www.myui.space
- **Preview URL**: https://preview.myui.space

## Project Settings

### Root Directory

**Critical for Monorepos**: The Vercel project must be configured with the correct root directory and build settings.

1. Navigate to [Project Settings → Build & Development Settings](https://vercel.com/idea-i/ideai-main/settings/general)
2. Find **Root Directory** setting
3. Set to: `apps/web`
4. **Enable** "Include files outside the root directory in the Build Step" checkbox
5. Save changes

**Why this matters:**
- Root Directory tells Vercel where to find the `package.json` and build the application
- "Include files outside the root directory" is **required** for Turborepo monorepos because:
  - The build needs access to the root `package.json`, `pnpm-workspace.yaml`, and `turbo.json`
  - Shared packages in `packages/` must be accessible
  - Without this, Vercel can't properly resolve workspace dependencies

See [Vercel's Build Configuration Documentation](https://vercel.com/docs/builds/configure-a-build#root-directory) for details.

### Build Configuration

Vercel automatically detects and configures Next.js applications. No `vercel.json` files are required when using the standard Turborepo + Vercel approach.

**Automatic Configuration:**
- Framework detection: Next.js (auto-detected from `package.json`)
- Build command: Auto-detected from `package.json` scripts
- Install command: Auto-detected from package manager (pnpm)
- Output directory: `.next` (Next.js default)

The Root Directory setting (`apps/web`) tells Vercel where to find the app, and Vercel handles the rest automatically.

## Vercel CLI

### Installation

```bash
npm install -g vercel
```

### Authentication

```bash
vercel login
```

### Linking Projects

Projects are linked via `.vercel/` directory:

```bash
# From repository root (Vercel uses Root Directory setting)
vercel link
```

This creates `.vercel/project.json` with project configuration.

**Note**: Vercel uses the Root Directory setting (`apps/web`) from the dashboard, so link from the repo root.

### Manual Deployment

```bash
# From repository root
# Preview deployment
vercel deploy

# Production deployment
vercel deploy --prod
```

**Note**: Deploy from repo root. Vercel automatically uses the Root Directory setting (`apps/web`) from the dashboard.

### Environment Variables

Pull environment variables locally:

```bash
# From repository root
vercel env pull .env.local
```

The `.env.local` file will be created in the current directory. Vercel uses the Root Directory setting to determine which app's environment variables to pull.

## Monorepo Configuration

### Standard Turborepo + Vercel Approach

This project uses the **standard Vercel boilerplate approach** for Turborepo monorepos:

1. **Root Directory** set in Vercel dashboard: `apps/web`
2. **Include files outside root** enabled (required for monorepos)
3. **Deploy from repo root** (no `working-directory` in workflows)
4. **Vercel auto-detects** Next.js and builds automatically

**How it works:**
- Vercel uses the Root Directory setting to find the app
- "Include files outside root" allows access to monorepo root files
- Vercel automatically detects Next.js from `package.json`
- Build commands run from the monorepo root context
- Shared packages in `packages/` are accessible during build

### Framework Detection

Vercel automatically detects Next.js when:
- Root Directory is set correctly (`apps/web`)
- `package.json` contains `next` dependency
- "Include files outside root directory" is enabled

## Deployment Process

### Automatic Deployment

1. Code pushed to GitHub
2. GitHub Actions workflow triggered
3. Build and test steps run
4. Vercel deployment initiated
5. Preview/production URL generated

### Deployment URLs

- **Preview**: `https://web-{hash}-idea-i.vercel.app`
- **Production**: `https://web-knac8m3pi-idea-i.vercel.app`

### Deployment Status

Check deployment status:
- [Vercel Dashboard](https://vercel.com/idea-i/web)
- GitHub Actions workflow logs
- Vercel CLI: `vercel inspect`

## Configuration Files

### .vercel/project.json

Generated by `vercel link`:

```json
{
  "projectId": "prj_rOeGwbNZwaO6sJ2J685Y3g9TV2cw",
  "orgId": "team_vhjzlMi6CfNow0IfBXnv2Yn2",
  "projectName": "web"
}
```

## Troubleshooting

### "Unexpected error" or Build Fails

**Symptoms**: Deployment queues but fails with "Unexpected error" or module resolution errors

**Solution**: This is almost always caused by missing monorepo configuration:
1. Set Root Directory to `apps/web` in [Project Settings](https://vercel.com/idea-i/web/settings/general)
2. **Enable** "Include files outside the root directory in the Build Step" checkbox
3. Save and redeploy

Without the "Include files outside the root directory" setting, Vercel can't access:
- Root `package.json` and workspace configuration
- Shared packages in `packages/`
- `turbo.json` for build orchestration

### "No Next.js version detected"

**Solution**: 
1. Set Root Directory to `apps/web` in Vercel project settings
2. Enable "Include files outside the root directory in the Build Step"

### Build Fails: "Cannot find module"

**Solution**: 
1. Ensure "Include files outside the root directory in the Build Step" is enabled
2. Verify Root Directory is set to `apps/web`
3. Check workspace dependencies are properly configured in `package.json`

### Deployment Fails: "Root Directory" error

**Solution**: Verify Root Directory setting matches app location (`apps/web`) in Vercel dashboard.

### Deployment Canceled: "Unverified commit"

**Solution**: This is Vercel's deployment protection. Options:
1. **Disable verification requirement** (for preview): Go to Project Settings → Deployment Protection → Disable "Require Verified Commits"
2. **Set up commit signing** (recommended): Configure GPG signing for commits (see [Commit Signing Setup](../setup/commit-signing.md))

## Best Practices

- ✅ Set Root Directory to `apps/web` in Vercel dashboard
- ✅ **Enable "Include files outside the root directory in the Build Step"** (required for monorepos)
- ✅ Deploy from repo root in GitHub Actions (no `working-directory` parameter)
- ✅ Let Vercel auto-detect Next.js framework (no `vercel.json` needed)
- ✅ Use environment variables for secrets
- ✅ Test deployments on preview before production
- ✅ Use standard Turborepo + Vercel boilerplate approach

## Related Documentation

- [Deployment Overview](./overview.md)
- [CI/CD Workflows](./ci-cd.md)
- [GitHub Secrets Setup](../setup/github-secrets.md)

