/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: 36
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types - step functions take any input
export type StepFunction = (input: any) => Promise<any>;

// Step modules may contain the step function plus other exports (types, constants, etc.)
// biome-ignore lint/suspicious/noExplicitAny: Dynamic module with mixed exports
export type StepModule = Record<string, any>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
  "ai-gateway/generate-text": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-text"),
    stepFunction: "generateTextStep",
  },
  "Generate Text": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-text"),
    stepFunction: "generateTextStep",
  },
  "ai-gateway/generate-image": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-image"),
    stepFunction: "generateImageStep",
  },
  "Generate Image": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-image"),
    stepFunction: "generateImageStep",
  },
  "blob/put": {
    importer: () => import("@/plugins/blob/steps/put"),
    stepFunction: "putBlobStep",
  },
  "blob/list": {
    importer: () => import("@/plugins/blob/steps/list"),
    stepFunction: "listBlobsStep",
  },
  "clerk/get-user": {
    importer: () => import("@/plugins/clerk/steps/get-user"),
    stepFunction: "clerkGetUserStep",
  },
  "clerk/create-user": {
    importer: () => import("@/plugins/clerk/steps/create-user"),
    stepFunction: "clerkCreateUserStep",
  },
  "clerk/update-user": {
    importer: () => import("@/plugins/clerk/steps/update-user"),
    stepFunction: "clerkUpdateUserStep",
  },
  "clerk/delete-user": {
    importer: () => import("@/plugins/clerk/steps/delete-user"),
    stepFunction: "clerkDeleteUserStep",
  },
  "fal/generate-image": {
    importer: () => import("@/plugins/fal/steps/generate-image"),
    stepFunction: "falGenerateImageStep",
  },
  "fal/generate-video": {
    importer: () => import("@/plugins/fal/steps/generate-video"),
    stepFunction: "falGenerateVideoStep",
  },
  "fal/upscale-image": {
    importer: () => import("@/plugins/fal/steps/upscale-image"),
    stepFunction: "falUpscaleImageStep",
  },
  "fal/remove-background": {
    importer: () => import("@/plugins/fal/steps/remove-background"),
    stepFunction: "falRemoveBackgroundStep",
  },
  "fal/image-to-image": {
    importer: () => import("@/plugins/fal/steps/image-to-image"),
    stepFunction: "falImageToImageStep",
  },
  "firecrawl/scrape": {
    importer: () => import("@/plugins/firecrawl/steps/scrape"),
    stepFunction: "firecrawlScrapeStep",
  },
  Scrape: {
    importer: () => import("@/plugins/firecrawl/steps/scrape"),
    stepFunction: "firecrawlScrapeStep",
  },
  "firecrawl/search": {
    importer: () => import("@/plugins/firecrawl/steps/search"),
    stepFunction: "firecrawlSearchStep",
  },
  Search: {
    importer: () => import("@/plugins/firecrawl/steps/search"),
    stepFunction: "firecrawlSearchStep",
  },
  "github/create-issue": {
    importer: () => import("@/plugins/github/steps/create-issue"),
    stepFunction: "createIssueStep",
  },
  "github/list-issues": {
    importer: () => import("@/plugins/github/steps/list-issues"),
    stepFunction: "listIssuesStep",
  },
  "github/get-issue": {
    importer: () => import("@/plugins/github/steps/get-issue"),
    stepFunction: "getIssueStep",
  },
  "github/update-issue": {
    importer: () => import("@/plugins/github/steps/update-issue"),
    stepFunction: "updateIssueStep",
  },
  "linear/create-ticket": {
    importer: () => import("@/plugins/linear/steps/create-ticket"),
    stepFunction: "createTicketStep",
  },
  "Create Ticket": {
    importer: () => import("@/plugins/linear/steps/create-ticket"),
    stepFunction: "createTicketStep",
  },
  "linear/find-issues": {
    importer: () => import("@/plugins/linear/steps/find-issues"),
    stepFunction: "findIssuesStep",
  },
  "Find Issues": {
    importer: () => import("@/plugins/linear/steps/find-issues"),
    stepFunction: "findIssuesStep",
  },
  "perplexity/search": {
    importer: () => import("@/plugins/perplexity/steps/search"),
    stepFunction: "perplexitySearchStep",
  },
  "perplexity/ask": {
    importer: () => import("@/plugins/perplexity/steps/ask"),
    stepFunction: "perplexityAskStep",
  },
  "perplexity/research": {
    importer: () => import("@/plugins/perplexity/steps/research"),
    stepFunction: "perplexityResearchStep",
  },
  "resend/send-email": {
    importer: () => import("@/plugins/resend/steps/send-email"),
    stepFunction: "sendEmailStep",
  },
  "Send Email": {
    importer: () => import("@/plugins/resend/steps/send-email"),
    stepFunction: "sendEmailStep",
  },
  "slack/send-message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message"),
    stepFunction: "sendSlackMessageStep",
  },
  "Send Slack Message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message"),
    stepFunction: "sendSlackMessageStep",
  },
  "stripe/create-customer": {
    importer: () => import("@/plugins/stripe/steps/create-customer"),
    stepFunction: "createCustomerStep",
  },
  "stripe/get-customer": {
    importer: () => import("@/plugins/stripe/steps/get-customer"),
    stepFunction: "getCustomerStep",
  },
  "stripe/create-invoice": {
    importer: () => import("@/plugins/stripe/steps/create-invoice"),
    stepFunction: "createInvoiceStep",
  },
  "superagent/guard": {
    importer: () => import("@/plugins/superagent/steps/guard"),
    stepFunction: "superagentGuardStep",
  },
  "superagent/redact": {
    importer: () => import("@/plugins/superagent/steps/redact"),
    stepFunction: "superagentRedactStep",
  },
  "v0/create-chat": {
    importer: () => import("@/plugins/v0/steps/create-chat"),
    stepFunction: "createChatStep",
  },
  "Create Chat": {
    importer: () => import("@/plugins/v0/steps/create-chat"),
    stepFunction: "createChatStep",
  },
  "v0/send-message": {
    importer: () => import("@/plugins/v0/steps/send-message"),
    stepFunction: "sendMessageStep",
  },
  "Send Message": {
    importer: () => import("@/plugins/v0/steps/send-message"),
    stepFunction: "sendMessageStep",
  },
  "webflow/list-sites": {
    importer: () => import("@/plugins/webflow/steps/list-sites"),
    stepFunction: "listSitesStep",
  },
  "webflow/get-site": {
    importer: () => import("@/plugins/webflow/steps/get-site"),
    stepFunction: "getSiteStep",
  },
  "webflow/publish-site": {
    importer: () => import("@/plugins/webflow/steps/publish-site"),
    stepFunction: "publishSiteStep",
  },
};

/**
 * Action labels - maps action IDs to human-readable labels
 * Used for displaying friendly names in the UI (e.g., Runs tab)
 */
export const ACTION_LABELS: Record<string, string> = {
  "ai-gateway/generate-text": "Generate Text",
  "ai-gateway/generate-image": "Generate Image",
  "blob/put": "Put Blob",
  "blob/list": "List Blobs",
  "clerk/get-user": "Get User",
  "clerk/create-user": "Create User",
  "clerk/update-user": "Update User",
  "clerk/delete-user": "Delete User",
  "fal/generate-image": "Generate Image",
  "fal/generate-video": "Generate Video",
  "fal/upscale-image": "Upscale Image",
  "fal/remove-background": "Remove Background",
  "fal/image-to-image": "Image to Image",
  "firecrawl/scrape": "Scrape URL",
  "firecrawl/search": "Search Web",
  "github/create-issue": "Create Issue",
  "github/list-issues": "List Issues",
  "github/get-issue": "Get Issue",
  "github/update-issue": "Update Issue",
  "linear/create-ticket": "Create Ticket",
  "linear/find-issues": "Find Issues",
  "perplexity/search": "Search Web",
  "perplexity/ask": "Ask Question",
  "perplexity/research": "Research Topic",
  "resend/send-email": "Send Email",
  "slack/send-message": "Send Slack Message",
  "stripe/create-customer": "Create Customer",
  "stripe/get-customer": "Get Customer",
  "stripe/create-invoice": "Create Invoice",
  "superagent/guard": "Guard",
  "superagent/redact": "Redact",
  "v0/create-chat": "Create Chat",
  "v0/send-message": "Send Message",
  "webflow/list-sites": "List Sites",
  "webflow/get-site": "Get Site",
  "webflow/publish-site": "Publish Site",
  Scrape: "Scrape URL",
  Search: "Search Web",
  "Generate Text": "Generate Text",
  "Generate Image": "Generate Image",
  "Send Email": "Send Email",
  "Create Ticket": "Create Ticket",
  "Find Issues": "Find Issues",
  "Send Slack Message": "Send Slack Message",
  "Create Chat": "Create Chat",
  "Send Message": "Send Message",
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}

/**
 * Get the human-readable label for an action type
 */
export function getActionLabel(actionType: string): string | undefined {
  return ACTION_LABELS[actionType];
}
